# Generated by Django 4.0.5 on 2022-06-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comment_post_associated_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvote',
            name='user_vote',
        ),
        migrations.AddField(
            model_name='postvote',
            name='profile_vote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_associated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='post_voted',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.post'),
        ),
    ]
