# Generated by Django 4.0.5 on 2022-06-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_postvote_user_vote_postvote_profile_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='post_voted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.post'),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='profile_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
    ]
