# Generated by Django 4.0.5 on 2022-06-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_postvote_post_voted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvote',
            name='vote',
        ),
        migrations.AlterField(
            model_name='postvote',
            name='profile_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='app.profile'),
        ),
    ]
