# Generated by Django 4.0.5 on 2022-06-06 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_postvote_vote_alter_postvote_profile_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvote',
            name='post_voted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='app.post'),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='profile_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile'),
        ),
    ]
